### ISSUE TITLE
Skidded

### ISSUE THREAD

**Issue by kisses4barbie** [Scripted1337/Discord-Group-Bomber#1]
Skidded off Marci's Code. (https://github.com/KAMKAZEMARCI/Discord-gc-spammer)

**Comment by Scripted1337** [comment]
> 
> 
> Skidded off Marci's Code. (https://github.com/KAMKAZEMARCI/Discord-gc-spammer)

thats literally the only way to do it in **requests**, other than discord.py so stfu
